# Generated by Django 4.1.3 on 2022-12-24 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursename', models.CharField(max_length=20)),
                ('fees', models.IntegerField()),
                ('comment', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
